package net.codejava.model1;
// Generated Aug 26, 2020 10:31:42 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", catalog = "projectMVC", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String nameVn;
	private Set products = new HashSet(0);
	private Set products_1 = new HashSet(0);

	public Category() {
	}

	public Category(String name, String nameVn) {
		this.name = name;
		this.nameVn = nameVn;
	}

	public Category(String name, String nameVn, Set products, Set products_1) {
		this.name = name;
		this.nameVn = nameVn;
		this.products = products;
		this.products_1 = products_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NameVN", nullable = false, length = 100)
	public String getNameVn() {
		return this.nameVn;
	}

	public void setNameVn(String nameVn) {
		this.nameVn = nameVn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getProducts_1() {
		return this.products_1;
	}

	public void setProducts_1(Set products_1) {
		this.products_1 = products_1;
	}

}
