package net.codejava.model1;
// Generated Aug 26, 2020 10:31:42 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "projectMVC")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String password;
	private String email;
	private String photo;
	private boolean activated;
	private boolean admin;
	private Set orders = new HashSet(0);

	public Customer() {
	}

	public Customer(String fullname, String password, String email, String photo, boolean activated, boolean admin) {
		this.fullname = fullname;
		this.password = password;
		this.email = email;
		this.photo = photo;
		this.activated = activated;
		this.admin = admin;
	}

	public Customer(String fullname, String password, String email, String photo, boolean activated, boolean admin,
			Set orders) {
		this.fullname = fullname;
		this.password = password;
		this.email = email;
		this.photo = photo;
		this.activated = activated;
		this.admin = admin;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Fullname", unique = true, nullable = false, length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "Password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Photo", nullable = false, length = 100)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Activated", nullable = false)
	public boolean isActivated() {
		return this.activated;
	}

	public void setActivated(boolean activated) {
		this.activated = activated;
	}

	@Column(name = "admin", nullable = false)
	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
