package net.codejava.model1;
// Generated Aug 26, 2020 10:31:42 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "Order_detail", catalog = "projectMVC")
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id;
	private Order order;
	private Product product;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id, Order order, Product product) {
		this.id = id;
		this.order = order;
		this.product = product;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unitPrce", column = @Column(name = "UnitPrce", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "quantity", column = @Column(name = "Quantity", nullable = false)),
			@AttributeOverride(name = "discount", column = @Column(name = "Discount", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "orderId", column = @Column(name = "OrderId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "ProductId", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderId", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
