package net.codejava.model1;
// Generated Aug 26, 2020 10:31:42 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", catalog = "projectMVC")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private Float unitPrice;
	private String image;
	private Date productDate;
	private boolean available;
	private int quantity;
	private String desctiption;
	private double discount;
	private int viewCount;
	private boolean special;
	private Set orderDetails = new HashSet(0);
	private Set orderDetails_1 = new HashSet(0);

	public Product() {
	}

	public Product(Category category, String name, String image, Date productDate, boolean available, int quantity,
			String desctiption, double discount, int viewCount, boolean special) {
		this.category = category;
		this.name = name;
		this.image = image;
		this.productDate = productDate;
		this.available = available;
		this.quantity = quantity;
		this.desctiption = desctiption;
		this.discount = discount;
		this.viewCount = viewCount;
		this.special = special;
	}

	public Product(Category category, String name, Float unitPrice, String image, Date productDate, boolean available,
			int quantity, String desctiption, double discount, int viewCount, boolean special, Set orderDetails,
			Set orderDetails_1) {
		this.category = category;
		this.name = name;
		this.unitPrice = unitPrice;
		this.image = image;
		this.productDate = productDate;
		this.available = available;
		this.quantity = quantity;
		this.desctiption = desctiption;
		this.discount = discount;
		this.viewCount = viewCount;
		this.special = special;
		this.orderDetails = orderDetails;
		this.orderDetails_1 = orderDetails_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryId", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "Name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "UnitPrice", precision = 12, scale = 0)
	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "Image", nullable = false, length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ProductDate", nullable = false, length = 10)
	public Date getProductDate() {
		return this.productDate;
	}

	public void setProductDate(Date productDate) {
		this.productDate = productDate;
	}

	@Column(name = "Available", nullable = false)
	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Desctiption", nullable = false, length = 200)
	public String getDesctiption() {
		return this.desctiption;
	}

	public void setDesctiption(String desctiption) {
		this.desctiption = desctiption;
	}

	@Column(name = "Discount", nullable = false, precision = 22, scale = 0)
	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	@Column(name = "ViewCount", nullable = false)
	public int getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}

	@Column(name = "Special", nullable = false)
	public boolean isSpecial() {
		return this.special;
	}

	public void setSpecial(boolean special) {
		this.special = special;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set getOrderDetails_1() {
		return this.orderDetails_1;
	}

	public void setOrderDetails_1(Set orderDetails_1) {
		this.orderDetails_1 = orderDetails_1;
	}

}
