package net.code.oas;
// Generated Aug 26, 2020 10:11:09 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private Date orderDate;
	private String address;
	private Double amount;
	private String description;
	private Set orderDetails = new HashSet(0);

	public Order() {
	}

	public Order(Customer customer, Date orderDate) {
		this.customer = customer;
		this.orderDate = orderDate;
	}

	public Order(Customer customer, Date orderDate, String address, Double amount, String description,
			Set orderDetails) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.address = address;
		this.amount = amount;
		this.description = description;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
