package net.code.oasa;
// Generated Aug 26, 2020 10:14:19 PM by Hibernate Tools 5.4.12.Final

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {

	private double unitPrce;
	private int quantity;
	private double discount;
	private int orderId;
	private int productId;
	private int id;

	public OrderDetailId() {
	}

	public OrderDetailId(double unitPrce, int quantity, double discount, int orderId, int productId, int id) {
		this.unitPrce = unitPrce;
		this.quantity = quantity;
		this.discount = discount;
		this.orderId = orderId;
		this.productId = productId;
		this.id = id;
	}

	public double getUnitPrce() {
		return this.unitPrce;
	}

	public void setUnitPrce(double unitPrce) {
		this.unitPrce = unitPrce;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return (this.getUnitPrce() == castOther.getUnitPrce()) && (this.getQuantity() == castOther.getQuantity())
				&& (this.getDiscount() == castOther.getDiscount()) && (this.getOrderId() == castOther.getOrderId())
				&& (this.getProductId() == castOther.getProductId()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUnitPrce();
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getDiscount();
		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getId();
		return result;
	}

}
